### ISSUE TITLE
Factor out BLAS-like functions into another module

### ISSUE THREAD

**Issue by rreusser** [rreusser/ndarray-gram-schmidt#1]
@mikolalysenko — this module includes code for the [inner product (DOT)](https://github.com/rreusser/ndarray-gram-schmidt/blob/master/gram-schmidt.js#L10), [AXPY](https://github.com/rreusser/ndarray-gram-schmidt/blob/master/gram-schmidt.js#L23), and [CPSC](https://github.com/rreusser/ndarray-gram-schmidt/blob/master/gram-schmidt.js#L28). Do these exist in another module? Should there be a module with basic blas-like operations? It looks like ndgemm is rather complicated, so there may be more subtlety than I'm aware of.

**Comment by mikolalysenko** [comment]
I definitely think you should factor them out.

Regarding ndgemm, I wouldn't use it as a great example.  It was kind of an experiment, and it works, but it is not in my opinion the right way to do things.  What I was trying to do with it was build something like cwise that could handle all the different special cases, but lately I've been leaning more toward just building a bunch of separate more specialized solvers and then integrating planners on top of them that can select optimized modules based on specific inputs.

**Comment by rreusser** [comment]
See: https://github.com/scijs/ndarray-blas-level1

Still debating for myself how much to split everything up. Went with just level 1 since level 2/3 might not all be so straightforward so best to separate. As for complex variables, still not clear whether to split everything into two repos or whether to add real + complex versions of the same operation to the same repo.
